Update update_submodules.yml by handling existing PRs

diff --git a/.github/workflows/update_submodules.yml b/.github/workflows/update_submodules.yml
--- a/.github/workflows/update_submodules.yml
+++ b/.github/workflows/update_submodules.yml
@@ -42,7 +42,27 @@ jobs:
         run: |
           git push origin submodule-update-branch --force || echo "Failed to push changes"
 
-      - name: Create Pull Request
+      - name: Check for Existing Pull Request
+        id: check_pr
+        env:
+          DB_TOKEN: ${{ secrets.DB_PAT }}
+        run: |
+          response=$(curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $DB_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${{ github.repository }}/pulls)
+          
+          echo "$response" | jq -r --arg branch "submodule-update-branch" '.[] | select(.head.ref == $branch) | .number' > pr_number.txt
+          if [[ -s pr_number.txt ]]; then
+            echo "Existing pull request found: $(<pr_number.txt)"
+            echo "pr_number=$(<pr_number.txt)" >> $GITHUB_ENV
+          else
+            echo "No existing pull request found."
+          fi
+
+      - name: Create or Update Pull Request
+        if: steps.check_pr.outputs.pr_number == ''
         env:
           DB_TOKEN: ${{ secrets.DB_PAT }}
         run: |
@@ -59,5 +79,27 @@ jobs:
 
           if [[ $(echo "$response" | jq -r '.id') == "null" ]]; then
             echo "Failed to create pull request."
+            exit 1
+          fi
+
+      - name: Update Existing Pull Request
+        if: steps.check_pr.outputs.pr_number != ''
+        env:
+          DB_TOKEN: ${{ secrets.DB_PAT }}
+          PULL_NUMBER: ${{ steps.check_pr.outputs.pr_number }}
+        run: |
+          response=$(curl -L \
+            -X PATCH \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $DB_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${{ github.repository }}/pulls/$PULL_NUMBER \
+            -d '{"title":"Automated Submodule Update","body":"This pull request updates the submodules to their latest versions.", "state":"open"}'
+          )
+          
+          echo "$response"
+
+          if [[ $(echo "$response" | jq -r '.id') == "null" ]]; then
+            echo "Failed to update pull request."
             exit 1
           fi
