Update update_submodules.yml by using newer -d format

diff --git a/.github/workflows/update_submodules.yml b/.github/workflows/update_submodules.yml
--- a/.github/workflows/update_submodules.yml
+++ b/.github/workflows/update_submodules.yml
@@ -38,8 +38,19 @@ jobs:
         run: |
           PR_TITLE="Automated Submodule Update"
           PR_BODY="This pull request updates the submodules to their latest versions."
-          curl --http1.1 -L -X POST -H "Accept: application/vnd.github+json" \
+          response=$(curl --http1.1 \
+            -L \
+            -X POST -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $DB_TOKEN" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"submodule-update-branch\",\"base\":\"master\"}" \
-            https://api.github.com/repos/${{ github.repository }}/pulls
+            https://api.github.com/repos/${{ github.repository }}/pulls \
+            -d '{"title":"'"$PR_TITLE"'","body":"'"$PR_BODY"'", "head":"submodule-update-branch", "base":"master"}'
+          )
+          
+          echo "$response"
+
+          if [[ $(echo "$response" | jq -r '.id') == "null" ]]; then
+            echo "Failed to create pull request."
+            exit 1
+          fi
+          
